# Generated by Django 4.1 on 2022-08-09 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('second_name', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100)),
                ('second_lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('register_number', models.AutoField(primary_key=True, serialize=False)),
                ('oxigen', models.FloatField(blank=True, null=True)),
                ('heart_rate', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('resp_rate', models.FloatField(blank=True, null=True)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('day_taken', models.PositiveIntegerField(blank=True, null=True)),
                ('year_taken', models.PositiveIntegerField(blank=True, null=True)),
                ('month_taken', models.PositiveIntegerField(blank=True, null=True)),
                ('hour_taken', models.PositiveIntegerField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehealt_databases.patient')),
            ],
            options={
                'db_table': 'vital_signs',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('user_account_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehealt_databases.patient')),
            ],
            options={
                'db_table': 'user_account',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumbers',
            fields=[
                ('phone_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('phone_content', models.CharField(blank=True, max_length=10, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehealt_databases.patient')),
            ],
            options={
                'db_table': 'phone_numbers',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehealt_databases.person'),
        ),
        migrations.CreateModel(
            name='DoctorAcount',
            fields=[
                ('doctor_account_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('doctor_username', models.CharField(blank=True, max_length=100, null=True)),
                ('doctor_email', models.CharField(blank=True, max_length=100, null=True)),
                ('doctor_password', models.CharField(blank=True, max_length=100, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehealt_databases.doctor')),
            ],
            options={
                'db_table': 'doctor_acount',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehealt_databases.person'),
        ),
        migrations.CreateModel(
            name='PatientDiagnostic',
            fields=[
                ('diagnostic_id', models.AutoField(primary_key=True, serialize=False)),
                ('diagnostic_text', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehealt_databases.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehealt_databases.patient')),
            ],
            options={
                'db_table': 'patient_diagnostic',
                'unique_together': {('diagnostic_id', 'doctor')},
            },
        ),
    ]
